// Copyright 2026 Inoue Kazuhiro (instreest). SPDX-License-Identifier: Apache-2.0
import { existsSync, readdirSync, statSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import * as path from 'node:path';
import { t } from './messages';

/**
 * 解析に使う設定（`jche.properties`）をどう用意するか。
 *
 * 優先順位は次のとおりで、上から順に当てはまった1つを使う（docs/vscode-plugin-design.md §3）。
 * 1. 利用者が設定（`jche.configFile`）で明示したファイル
 * 2. ワークスペースフォルダ直下の `*.properties`（`jche.properties` を先頭に、次に以前の名前の `config.properties`、
 *    ほかは名前順。`launcher.properties` は除く。複数あれば呼び出し側が選ばせる）
 * 3. どれも無ければ自動生成 … **`project.root` だけ**書いた最小の設定
 *
 * 自動生成で `source.folders` や `library.folders` を書かないのは意図的である。
 * 空欄なら本体の `ProjectDetector` が `project.root` の中身（`pom.xml` / `build.gradle` /
 * フォルダ構成）から決めるので、こちらで推測し直す必要が無い。Eclipse 版はプロジェクトの
 * クラスパスを持っているのでそれを翻訳しているが、VSCode は持っていない（vscode-java に
 * 頼れば取れるが、公開 API でないコマンドに寄りかかることになる）。
 *
 * このモジュールは `vscode` を使わない。VSCode 無しで検査できるようにするため。
 */

export type ConfigSource =
    | { readonly kind: 'file'; readonly file: string }
    | { readonly kind: 'generated'; readonly projectRoot: string };

/** 画面に出す説明。「どの設定で解析したか」が分からないまま結果だけ見せない */
export function labelOf(source: ConfigSource, workspaceRoot: string): string {
    return source.kind === 'file'
        ? path.relative(workspaceRoot, source.file) || path.basename(source.file)
        : t('config.autoGenerated');
}

/**
 * フォルダ直下にある設定ファイルの候補。`jche.properties` を先頭に、ほかの `*.properties` は名前順
 * （設定ファイルをプロジェクトごとに増やす使い方があるため）。以前の名前の `config.properties` に特別な
 * 扱いは無い（解析対象のプロジェクトが自前の設定に使っていることがあるため。ほかの名前と同じく候補には並ぶ）。
 * `launcher.properties` は起動コマンドの設定なので除く。
 */
const PREFERRED_NAMES = ['jche.properties'];
function nameRank(name: string): number {
    const i = PREFERRED_NAMES.indexOf(name);
    return i < 0 ? PREFERRED_NAMES.length : i;
}

export function findConfigFiles(folder: string): string[] {
    if (!existsSync(folder) || !statSync(folder).isDirectory()) {
        return [];
    }
    const names = readdirSync(folder)
        .filter((name) => name.endsWith('.properties') && name !== 'launcher.properties')
        .filter((name) => statSync(path.join(folder, name)).isFile())
        .sort((a, b) => nameRank(a) - nameRank(b) || a.localeCompare(b));
    return names.map((name) => path.join(folder, name));
}

/**
 * 設定の出どころを決める。
 *
 * @param workspaceRoot ワークスペースフォルダ
 * @param explicit      設定 `jche.configFile`（相対ならワークスペースフォルダ起点）。空なら無し
 * @param remembered    前回このフォルダで選んだ設定ファイル。無ければ undefined
 * @returns 決まった出どころ。候補が複数あって決められないときは `choices` に候補を返す
 */
export function resolveConfigSource(
    workspaceRoot: string,
    explicit: string | undefined,
    remembered: string | undefined,
): { readonly source?: ConfigSource; readonly choices?: string[]; readonly error?: string } {
    if (explicit && explicit.trim() !== '') {
        const file = path.resolve(workspaceRoot, explicit.trim());
        if (!existsSync(file) || !statSync(file).isFile()) {
            return { error: t('config.fileMissing', file) };
        }
        return { source: { kind: 'file', file } };
    }
    const candidates = findConfigFiles(workspaceRoot);
    if (candidates.length === 0) {
        return { source: { kind: 'generated', projectRoot: workspaceRoot } };
    }
    if (candidates.length === 1) {
        return { source: { kind: 'file', file: candidates[0] } };
    }
    if (remembered && candidates.includes(remembered)) {
        return { source: { kind: 'file', file: remembered } };
    }
    return { choices: candidates };
}

/**
 * 設定ファイルの中の、**Java を実行させる項目**。
 *
 * `plugin.folders` のフォルダに置かれた `.java` は解析のたびにコンパイルされて動き、
 * `resolver.candidate.providers` / `call.rules.providers` はそこから読み込むクラスの名前である
 * （本体の `jche.config.Plugins` / `PluginClassLoaders`）。つまり解析対象のリポジトリに置かれた
 * `jche.properties` は、そのリポジトリの Java を利用者の PC で動かせる。
 * 利用者が明示した設定ではなく**フォルダから自動で拾った設定**にこれらがあるときは、
 * 解析の前に一度だけ確かめる（`session.ts`）。
 */
export const CODE_EXECUTING_KEYS = ['plugin.folders', 'resolver.candidate.providers', 'call.rules.providers'] as const;

/**
 * 設定ファイルの中身から、値の入った {@link CODE_EXECUTING_KEYS} を返す（並びは表の順）。
 *
 * 読み方は本体の `jche.config.ConfigFile` と同じ: 1 行に `項目=値`、`#` / `!` で始まる行は注釈、
 * 行末の `\` か字下げで次の行へ続く（`項目=` の形の行は字下げされていても項目の行。空行は字下げの続きを切る）。
 * 読めない行（`=` が無い等）は本体が解析のときにエラーにするので、ここでは読み飛ばすだけでよい。
 */
export function codeExecutingKeys(text: string): string[] {
    const values = new Map<string, string>();
    let currentKey: string | undefined;
    let currentValue = '';
    let pending = false;    // 直前の内容行が \ で終わっている（次の内容行に続く）
    const flush = () => {
        if (currentKey !== undefined) {
            values.set(currentKey, currentValue);
        }
        currentKey = undefined;
        currentValue = '';
    };
    const lines = text.split(/\r?\n/);
    for (let i = 0; i < lines.length; i++) {
        const line = (i === 0) ? lines[i].replace(/^\uFEFF/, '') : lines[i];
        const trimmed = line.trim();
        if (trimmed.startsWith('#') || trimmed.startsWith('!')) {
            continue;
        }
        if (trimmed === '') {
            if (!pending) {
                flush();
            }
            continue;
        }
        const indented = /^\s/.test(line);
        const keyLike = /^\s*[A-Za-z][A-Za-z0-9._-]*\s*=/.test(line);
        if (currentKey !== undefined && !keyLike && (pending || indented)) {
            pending = trimmed.endsWith('\\');
            currentValue += withoutTrailingBackslash(trimmed);
            continue;
        }
        flush();
        const eq = trimmed.indexOf('=');
        if (eq < 0) {
            continue;
        }
        const value = trimmed.substring(eq + 1).trim();
        pending = value.endsWith('\\');
        currentKey = trimmed.substring(0, eq).trim();
        currentValue = withoutTrailingBackslash(value);
    }
    flush();
    return CODE_EXECUTING_KEYS.filter((key) => (values.get(key) ?? '') !== '');
}

/** 行末の `\`（続きの印）を除き、その前の空白も落とす */
function withoutTrailingBackslash(s: string): string {
    return s.endsWith('\\') ? s.substring(0, s.length - 1).trim() : s;
}

/**
 * 自動生成する設定の中身。`project.root` は絶対パスで書く（生成ファイルは拡張のストレージに
 * 置くので、相対にするとそこが起点になってしまう）。
 * 値はそのまま書く。読み手（本体の `jche.config.ConfigFile`）はバックスラッシュをエスケープとして
 * 読まないので、Windows のパスを逃がす必要は無い（`\\` と重ねると、そのまま 2 つのバックスラッシュとして読まれる）。
 */
export function generatedConfigText(projectRoot: string): string {
    return [
        t('config.header.generated1'),
        t('config.header.generated2'),
        t('config.header.generated3'),
        t('config.header.generated4'),
        `project.root=${path.resolve(projectRoot)}`,
        '',
    ].join('\n');
}

/** ワークスペースへ書き出すときの中身。こちらは `project.root=.` で、項目の説明を付ける */
export function savedConfigText(): string {
    return [
        t('config.header.saved1'),
        t('config.header.saved2'),
        t('config.header.saved3'),
        'project.root=.',
        t('config.header.saved4'),
        'source.folders=',
        'library.folders=',
        'source.encoding=',
        'source.level=',
        t('config.header.saved5'),
        'entry.packages=',
        'exclude.packages=',
        '',
    ].join('\n');
}

/**
 * 子プロセスへ渡すための設定ファイルのパスを返す。
 * 自動生成のときは、渡されたフォルダに書き出す（次の解析でも同じ場所を使い回す）。
 *
 * @param scratchDir 一時ファイルの置き場所（拡張のストレージの下）
 */
export async function materialize(source: ConfigSource, scratchDir: string): Promise<string> {
    if (source.kind === 'file') {
        return source.file;
    }
    await mkdir(scratchDir, { recursive: true });
    const generated = path.join(scratchDir, 'generated-config.properties');
    // Config は UTF-8 で読むので、パスに日本語が入っても壊れない
    await writeFile(generated, generatedConfigText(source.projectRoot), 'utf8');
    return generated;
}
